services:
  - type: web
    name: uhakix-api
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: NVIDIA_API_KEY
        value: ${NVIDIA_API_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: PORT
        value: 10000        
