name: UHAKIX CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Smart contract tests
  contract-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: blockchain/package.json
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat test
